// Package catalogue is the single answer to "which apps does this instance
// publish", and the three files that answer has to reach.
//
// This is the reason Holistic exists as a component rather than a folder. One
// decision by one person fans out into three configurations owned by three
// different programs:
//
//	Warpgate   apps[]                  -> a DNS record and an ingress rule
//	coreX      instance.appOrigins     -> what /api/instance advertises, and
//	                                      therefore which apps the launcher offers
//	Solisuite  apps[] with host+origin -> the Host -> app map appFor() needs
//
// None of the three can see the other two. The Solisuite half is generated by
// nothing at all today, and appFor() is inert without it — so the practical
// state of the landscape before this package was that publishing an app meant
// editing three files by hand and finding out you had missed one when a
// hostname served the wrong document.
//
// Nothing here contains a domain. Hostnames are derived from one that is passed
// in, which is the rule the whole landscape is built on: the instance's domain
// exists in exactly one file on one machine.
package catalogue

import (
	"errors"
	"fmt"
	"sort"
	"strings"
)

// App is one thing the instance publishes at <id>.<domain>.
type App struct {
	// ID is the subdomain label and the identity everything else keys on.
	ID string `json:"id"`
	// Label is what a person sees in the launcher.
	Label string `json:"label"`
	Icon  string `json:"icon,omitempty"`
	// Upstream is the internal address traffic is handed to. Never public.
	Upstream string `json:"upstream"`
	// Enabled is the checkbox in the wizard.
	Enabled bool `json:"enabled"`
	// Protocols this route must carry beyond plain HTTP. Only "sse" changes
	// anything today; the rest are recorded and inert, and are marked as such
	// rather than left to read as promises.
	Protocols []string `json:"protocols,omitempty"`
	// Standalone marks an app that is not served by Solisuite — RoomSense has
	// its own server. It still needs DNS and ingress, and must NOT appear in
	// Solisuite's app list, where it would map a Host to a document that does
	// not exist.
	Standalone bool `json:"standalone,omitempty"`
	// Required marks an app the instance does not work without. The wizard
	// shows these as checked and refuses to uncheck them, rather than letting
	// somebody build an instance with no way to sign in.
	Required bool `json:"required,omitempty"`
	// Note is shown next to the checkbox.
	Note string `json:"note,omitempty"`
}

// Default is the catalogue a fresh instance starts from. It is a function
// rather than a package variable so that a caller cannot mutate the defaults
// for everybody else — the wizard hands this straight to a UI that edits it.
func Default() []App {
	return []App{
		{ID: "launcher", Label: "Launcher", Upstream: solisuite, Enabled: true, Required: true,
			Note: "The way in. Every other app is reached from here."},
		{ID: "mail", Label: "Mail", Upstream: solisuite, Enabled: true, Protocols: []string{"sse"}},
		{ID: "calendar", Label: "Calendar", Upstream: solisuite, Enabled: true, Protocols: []string{"sse"}},
		{ID: "contacts", Label: "Contacts", Upstream: solisuite, Enabled: true},
		{ID: "files", Label: "Files", Upstream: solisuite, Enabled: true},
		{ID: "gallery", Label: "Gallery", Upstream: solisuite, Enabled: false},
		{ID: "assistant", Label: "Assistant", Upstream: solisuite, Enabled: false, Protocols: []string{"sse"},
			Note: "Needs a local model or a Claude CLI on this machine."},
		{ID: "system", Label: "System", Upstream: solisuite, Enabled: true, Protocols: []string{"sse"},
			Note: "Administration. Visible to administrators only."},
		{ID: "roomsense", Label: "RoomSense", Upstream: roomsense, Enabled: false, Standalone: true,
			Note: "Its own service, not part of Solisuite."},
	}
}

// The upstreams are the ports the units in this landscape bind. They are
// internal addresses, not instance configuration, which is why they are
// constants here and the domain never is.
const (
	solisuite = "http://127.0.0.1:8795"
	roomsense = "http://127.0.0.1:8797"
)

// Catalogue is the decision, plus the domain it is expressed under.
type Catalogue struct {
	Domain string
	Apps   []App
}

func New(domain string, apps []App) Catalogue {
	return Catalogue{Domain: strings.TrimSpace(strings.ToLower(domain)), Apps: apps}
}

var (
	ErrNoDomain   = errors.New("the catalogue has no domain, so no hostname can be derived")
	ErrNoLauncher = errors.New("the launcher is disabled, which would leave no way in")
)

// Validate refuses catalogues that would produce a broken instance.
func (c Catalogue) Validate() error {
	if c.Domain == "" {
		return ErrNoDomain
	}
	if strings.ContainsAny(c.Domain, "/: ") {
		return fmt.Errorf("%q is not a bare domain", c.Domain)
	}
	seen := map[string]bool{}
	launcher := false
	for _, a := range c.Apps {
		if a.ID == "" {
			return errors.New("every app needs an id — it becomes the subdomain")
		}
		if seen[a.ID] {
			return fmt.Errorf("app %q appears twice", a.ID)
		}
		seen[a.ID] = true
		if a.Enabled && a.Upstream == "" {
			return fmt.Errorf("app %q is enabled with no upstream", a.ID)
		}
		if a.Required && !a.Enabled {
			return fmt.Errorf("app %q cannot be disabled", a.ID)
		}
		if a.ID == "launcher" && a.Enabled {
			launcher = true
		}
	}
	if !launcher {
		return ErrNoLauncher
	}
	return nil
}

// Hostname is where an app answers. The one place a hostname is composed.
func (c Catalogue) Hostname(id string) string { return id + "." + c.Domain }

// Origin is the URL other components record for an app. https, always: the
// only way in from outside is the tunnel, and the tunnel terminates TLS.
func (c Catalogue) Origin(id string) string { return "https://" + c.Hostname(id) }

// Enabled returns the chosen apps, in a stable order.
func (c Catalogue) Enabled() []App {
	var out []App
	for _, a := range c.Apps {
		if a.Enabled {
			out = append(out, a)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// --- the three projections -------------------------------------------------

// WarpgateApp mirrors Warpgate's config.App. It is duplicated rather than
// imported: Holistic writes a JSON file that Warpgate reads, and a shared Go
// type would make one repository's refactor break another's file format
// silently. The file is the contract.
type WarpgateApp struct {
	Name      string   `json:"name"`
	Upstream  string   `json:"upstream"`
	Protocols []string `json:"protocols,omitempty"`
	Comment   string   `json:"comment,omitempty"`
}

// Warpgate is what becomes DNS and ingress.
func (c Catalogue) Warpgate() []WarpgateApp {
	var out []WarpgateApp
	for _, a := range c.Enabled() {
		w := WarpgateApp{Name: a.ID, Upstream: a.Upstream, Protocols: a.Protocols, Comment: a.Note}
		out = append(out, w)
	}
	return out
}

// SolisuiteApp mirrors Solisuite's server config.
type SolisuiteApp struct {
	ID     string `json:"id"`
	Label  string `json:"label"`
	Icon   string `json:"icon,omitempty"`
	Host   string `json:"host"`
	Origin string `json:"origin"`
}

// Solisuite is the Host -> app map appFor() needs, and which nothing generated
// before. Standalone apps are excluded: RoomSense has its own server, and
// listing it here would map its hostname to a Solisuite document that does not
// exist.
func (c Catalogue) Solisuite() []SolisuiteApp {
	var out []SolisuiteApp
	for _, a := range c.Enabled() {
		if a.Standalone {
			continue
		}
		out = append(out, SolisuiteApp{
			ID: a.ID, Label: a.Label, Icon: a.Icon,
			Host: c.Hostname(a.ID), Origin: c.Origin(a.ID),
		})
	}
	return out
}

// CoreXOrigins is what /api/instance advertises, and therefore which apps the
// launcher offers.
//
// proven is the set of app ids whose hostname has actually answered a probe
// from the public internet. Apps are added as they are proven rather than all
// at once, for a reason worth keeping: an origin map listing eight hostnames
// that do not resolve is the populated-but-wrong state that shipped once
// already, and writing it incrementally turns the launcher into an honest
// progress display for free — shellApps() already filters to apps that have an
// origin.
//
// Passing nil means "none proven yet" and yields an empty map, not every app.
func (c Catalogue) CoreXOrigins(proven map[string]bool) map[string]string {
	out := map[string]string{}
	for _, a := range c.Enabled() {
		if a.Standalone {
			// coreX serves no API for it and the launcher cannot open it as
			// one of its own.
			continue
		}
		if proven[a.ID] {
			out[a.ID] = c.Origin(a.ID)
		}
	}
	return out
}

// Hostnames is every name that has to resolve for this catalogue to be true —
// the list the wizard probes, one nonce request each.
func (c Catalogue) Hostnames() []string {
	var out []string
	for _, a := range c.Enabled() {
		out = append(out, c.Hostname(a.ID))
	}
	return out
}
